### ISSUE TITLE
就你 group 多

### ISSUE THREAD

**Issue by Dafrok** [C8H16O2/Actuality#1]

**Comment by shinux** [comment]
![image](https://cloud.githubusercontent.com/assets/7784713/24739737/0427dc42-1ad0-11e7-88c9-386937d18438.png)

**Comment by blade254353074** [comment]
关于 @shinux  Group 多的问题，我已经和它私下解决了~
@Dafrok  如果有问题再开吧。

**Comment by shinux** [comment]
......

**Comment by Dafrok** [comment]
……
